apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: {{ .Values.namespace }}
data:
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: ecommerce
  MYSQL_USER: ecommerce
