namespace: ecommerce

backend:
  replicaCount: 2
  image:
    repository: YOUR_AWS_ACCOUNT_ID.dkr.ecr.YOUR_REGION.amazonaws.com/cloud-ecommerce-backend
    tag: latest
  service:
    port: 8000

frontend:
  replicaCount: 2
  image:
    repository: YOUR_AWS_ACCOUNT_ID.dkr.ecr.YOUR_REGION.amazonaws.com/cloud-ecommerce-frontend
    tag: latest
  service:
    port: 80

mysql:
  image: mysql:8.4
  storage: 5Gi
